### ISSUE TITLE
Incorrect time shown on reports

### ISSUE THREAD

**Issue by prittandrani** [urbanriskmap/petabencana.id#143]
Hi @talltom thanks for the time stamp reports! Following the updates on [https://github.com/urbanriskmap/petabencana.id/issues/104](url) I noticed that there is a mismatch only on some reports (I am guessing that they are the reports from Qlue?)

Reports with incorrect time:
![20170119 _ time stamp report qlue](https://cloud.githubusercontent.com/assets/22338984/22095765/fff2a372-de49-11e6-9468-61349f3e6b1f.PNG)

Reports with correct time (test report from Twitter):
![20170119 _ time stamp report twitter](https://cloud.githubusercontent.com/assets/22338984/22095772/0af79d40-de4a-11e6-9424-8c2e2521c356.PNG)

P.S i opened this new issue because I can't reopen the time stamp reports issue... Thanks :)

**Comment by prittandrani** [comment]
Also, just want to check are the reports set to disappear in 2 hours? The Qlue report above is still shown until now (16:46) but the Twitter one already gone. :) cc @anexact @fadmastuti .

**Comment by talltom** [comment]
Hi Pritta, OK thanks for this. I think it is probably because Qlue does not specify a time zone. 

I'm going to make some notes below so we can investigate further.

**Comment by talltom** [comment]
Original qlue report: https://gist.github.com/anonymous/89e88b94c96595199ba2376199a090a2
Resulting petabencana.id report: https://data.petabencana.id/reports/729

**Comment by talltom** [comment]
OK, it looks like this was because of a typo when setting the timezone of Qlue reports as they entered CogniCity.

@prittandrani - I think I've fixed this, please check over the next day or so to see if the time stamps look correct? Note that Qlue reports with the incorrect time stamp will be on the map for the next hour.

@matthewberryman - I made this minor change (https://github.com/urbanriskmap/cognicity-reports-lambda/commit/7920355a9972feb43514ffbcf660d1f0833f3819), pushed to master and built cognicity-server-lambda-prod.

**Comment by matthewberryman** [comment]
@talltom For reference the reports lambda stuff is in cognicity-reports-lambda, and jenkins builds are triggered automatically for lambdas too.

**Comment by prittandrani** [comment]
Hi @talltom, I checked this morning and it still shows incorrect time (it
is 10.43am but the report shows it is from 1 pm on the same day).

**Comment by prittandrani** [comment]
![image](https://cloud.githubusercontent.com/assets/22338984/22171726/1d095216-dfc7-11e6-8726-76f7270fb98b.png)

**Comment by talltom** [comment]
Hi Pritta, would you mind testing this with the original device and browser you originally spotted the bug in?

It seems that Safari in your most recent screenshots is doing something strange as it shouldn't be adding "GMT+7" so I think there are multiple issues here.

**Comment by talltom** [comment]
Hi, I was able to confirm my suspicions:

- Safari 8 iOS 8.1 time stamp is incorrectly displayed by the browser:
<img width="323" alt="screen shot 2017-01-22 at 12 25 37 pm" src="https://cloud.githubusercontent.com/assets/944642/22184410/c9d0e324-e09e-11e6-850e-1bcf69187e9c.png">

- Safari 10 iOS 10.2 time stamp is correctly displayed by the browser:
<img width="323" alt="screen shot 2017-01-22 at 12 28 32 pm" src="https://cloud.githubusercontent.com/assets/944642/22184420/e7286a78-e09e-11e6-86bc-194abf87cec2.png">

**Comment by prittandrani** [comment]
Hi @talltom sure, but as now there is no report on the map I will do it and report back soon as we have some reports.
